# Generated by Django 4.2.7 on 2023-12-03 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True, verbose_name='Correo Electrónico')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellidos')),
                ('is_instructor', models.BooleanField(blank=True, null=True, verbose_name='¿Profesor?')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('identification', models.IntegerField(unique=True, verbose_name='Cédula')),
                ('cell_phone', models.IntegerField(verbose_name='Celular')),
                ('guardians_name', models.CharField(max_length=100, verbose_name='Nombre del Acudiente')),
                ('guardians_phone', models.IntegerField(verbose_name='Celular del Acudiente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('identification', models.IntegerField(unique=True, verbose_name='Cédula')),
                ('cell_phone', models.IntegerField(verbose_name='Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del curso')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.instructormodel')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
